apiVersion: hive.openshift.io/v1
kind: ClusterDeployment
metadata:
  name: sno-cluster2
  namespace: assisted-installer
spec:
  baseDomain: znero.local
  clusterName: sno-cluster2
  pullSecretRef:
    name: pull-secret
  clusterInstallRef:
    group: extensions.hive.openshift.io
    kind: AgentClusterInstall
    name: sno-cluster2-install
    version: v1beta1
  platform:
    agentBareMetal:
      agentSelector:
        matchLabels:
          cluster-name: sno-cluster2
  installAttemptsLimit: 0
