apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Namespace padr√£o aplicado a todos os manifests
namespace: ocp-cli1

# Manifests principais do cluster
resources:
- 01-namespace.yaml
- 02-cluster-deployment.yaml
- 03-agent-cluster-install.yaml
- 04-infra-env.yaml

- hosts/host1/nmstate.yaml
- hosts/host1/baremetalhost.yaml

- hosts/host2/nmstate.yaml
- hosts/host2/baremetalhost.yaml

- hosts/host3/nmstate.yaml
- hosts/host3/baremetalhost.yaml

# Labels comuns para facilitar filtragem
commonLabels:
  app: ztp-cluster-install
  cluster-name: ocp-cli1
  site: site-cliente-1
